# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\x07\n\x05\x45mpty\"G\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\".\n\x08Products\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product\"\x82\x01\n\x0cMergeRequest\x12/\n\x05input\x18\x01 \x03(\x0b\x32 .product.MergeRequest.InputEntry\x1a\x41\n\nInputEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.product.InputValue:\x02\x38\x01\"c\n\nInputValue\x12\x14\n\x0cstring_value\x18\x01 \x01(\t\x12\x14\n\x0c\x64ouble_value\x18\x02 \x01(\x01\x12)\n\x0cnested_value\x18\x03 \x01(\x0b\x32\x13.product.InputValue2\xe9\x01\n\x0eProductService\x12\x33\n\x0eGetNewProducts\x12\x0e.product.Empty\x1a\x11.product.Products\x12\x34\n\x10MarkProductSaved\x12\x10.product.Product\x1a\x0e.product.Empty\x12\x35\n\x10GetSavedProducts\x12\x0e.product.Empty\x1a\x11.product.Products\x12\x35\n\x0c\x44\x65\x62ugService\x12\x15.product.MergeRequest\x1a\x0e.product.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MERGEREQUEST_INPUTENTRY']._loaded_options = None
  _globals['_MERGEREQUEST_INPUTENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_PRODUCT']._serialized_start=35
  _globals['_PRODUCT']._serialized_end=106
  _globals['_PRODUCTS']._serialized_start=108
  _globals['_PRODUCTS']._serialized_end=154
  _globals['_MERGEREQUEST']._serialized_start=157
  _globals['_MERGEREQUEST']._serialized_end=287
  _globals['_MERGEREQUEST_INPUTENTRY']._serialized_start=222
  _globals['_MERGEREQUEST_INPUTENTRY']._serialized_end=287
  _globals['_INPUTVALUE']._serialized_start=289
  _globals['_INPUTVALUE']._serialized_end=388
  _globals['_PRODUCTSERVICE']._serialized_start=391
  _globals['_PRODUCTSERVICE']._serialized_end=624
# @@protoc_insertion_point(module_scope)
