# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import application.util.grpc_utils.product_pb2 as product__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNewProducts = channel.unary_unary(
                '/product.ProductService/GetNewProducts',
                request_serializer=product__pb2.Empty.SerializeToString,
                response_deserializer=product__pb2.Products.FromString,
                _registered_method=True)
        self.MarkProductSaved = channel.unary_unary(
                '/product.ProductService/MarkProductSaved',
                request_serializer=product__pb2.Product.SerializeToString,
                response_deserializer=product__pb2.Empty.FromString,
                _registered_method=True)
        self.GetSavedProducts = channel.unary_unary(
                '/product.ProductService/GetSavedProducts',
                request_serializer=product__pb2.Empty.SerializeToString,
                response_deserializer=product__pb2.Products.FromString,
                _registered_method=True)
        self.DebugService = channel.unary_unary(
                '/product.ProductService/DebugService',
                request_serializer=product__pb2.MergeRequest.SerializeToString,
                response_deserializer=product__pb2.Empty.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNewProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkProductSaved(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSavedProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DebugService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNewProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNewProducts,
                    request_deserializer=product__pb2.Empty.FromString,
                    response_serializer=product__pb2.Products.SerializeToString,
            ),
            'MarkProductSaved': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkProductSaved,
                    request_deserializer=product__pb2.Product.FromString,
                    response_serializer=product__pb2.Empty.SerializeToString,
            ),
            'GetSavedProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSavedProducts,
                    request_deserializer=product__pb2.Empty.FromString,
                    response_serializer=product__pb2.Products.SerializeToString,
            ),
            'DebugService': grpc.unary_unary_rpc_method_handler(
                    servicer.DebugService,
                    request_deserializer=product__pb2.MergeRequest.FromString,
                    response_serializer=product__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNewProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetNewProducts',
            product__pb2.Empty.SerializeToString,
            product__pb2.Products.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkProductSaved(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/MarkProductSaved',
            product__pb2.Product.SerializeToString,
            product__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSavedProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetSavedProducts',
            product__pb2.Empty.SerializeToString,
            product__pb2.Products.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DebugService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/DebugService',
            product__pb2.MergeRequest.SerializeToString,
            product__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
